name: build

env:
  RUST_BACKTRACE: full

# only perform these build steps on pre-release or forced dev build
on:
  push:
    tags:
      - "v*-pre.*"
      - "*.dev-build.*"

jobs:
  build-and-pre-release-mac:
    permissions:
      contents: write
    strategy:
      matrix:
        runner-tags: [[self-hosted, macOS, X64]]
        include:
          - runner-tags: [self-hosted, macOS, X64]
            container: ""

    runs-on: ${{ matrix.runner-tags }}
    container: ${{ matrix.container }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # - name: Brew Bundle
      #   if: runner.os == 'macOS'
      #   run: |
      #     brew bundle

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-09-18
          override: true
          components: rustfmt, clippy

      - name: Cargo Build
        run: |
          make mac

      - name: Copy binaries to cache folder
        run: |
          mkdir -pv build_artifacts
          cp target/x86_64-apple-darwin/release/burrito.zip build_artifacts/burrito-mac64.zip

      - name: Create Artifact
        run: |
          mkdir -pv artifact
          cd artifact && cp ../build_artifacts/burrito-mac64.zip ./burrito-mac64-${{ github.sha }}.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: burrito
          path: artifact/burrito-mac64-${{ github.sha }}.zip

      - name: Create Prerelease
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir -pv release
          cd release && cp ../build_artifacts/burrito-mac64.zip ./burrito-mac64-${{ github.ref_name }}.zip

      - name: Upload Prerelease
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          files: |
            release/burrito-mac64-${{ github.ref_name }}.zip
  build-and-pre-release:
    permissions:
      contents: write
    strategy:
      matrix:
        runner-tags: [[self-hosted, Linux, X64]]
        include:
          - runner-tags: [self-hosted, Linux, X64]
            container: ""

    runs-on: ${{ matrix.runner-tags }}
    container: ${{ matrix.container }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-09-18
          override: true
          components: rustfmt, clippy

      - name: Cargo Build
        run: |
          make linux
          make win
          make win32

      - name: Copy binaries to cache folder
        run: |
          mkdir -pv build_artifacts
          cp target/x86_64-unknown-linux-gnu/release/burrito.zip build_artifacts
          cp target/x86_64-pc-windows-gnu/release/burrito.zip build_artifacts/burrito-win64.zip
          cp target/i686-pc-windows-gnu/release/burrito.zip build_artifacts/burrito-win32.zip

      - name: Create Artifact
        run: |
          mkdir -pv artifact
          cd artifact
          cp ../build_artifacts/burrito.zip ./burrito-linux-${{ github.sha }}.zip
          cp ../build_artifacts/burrito-win64.zip ./burrito-win64-${{ github.sha }}.zip
          cp ../build_artifacts/burrito-win32.zip ./burrito-win32-${{ github.sha }}.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: burrito
          path: artifact/burrito-linux-${{ github.sha }}.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: burrito
          path: artifact/burrito-win64-${{ github.sha }}.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: burrito
          path: artifact/burrito-win32-${{ github.sha }}.zip

      - name: Create Prerelease
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir -pv release
          cd release
          cp ../build_artifacts/burrito.zip ./burrito-linux-${{ github.ref_name }}.zip
          cp ../build_artifacts/burrito-win64.zip ./burrito-win64-${{ github.ref_name }}.zip
          cp ../build_artifacts/burrito-win32.zip ./burrito-win32-${{ github.ref_name }}.zip

      - name: Upload Prerelease
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          files: |
            release/burrito-linux-${{ github.ref_name }}.zip
            release/burrito-win64-${{ github.ref_name }}.zip
            release/burrito-win32-${{ github.ref_name }}.zip

