name: release

# only perform these build steps on non-pre-release
on:
  push:
    tags:
      - "v*"
      - "!v*-pre*"

jobs:
  release:
    runs-on: [self-hosted, macOS]
    # Needs write permission for publishing release
    permissions:
      contents: write

    steps:
      - name: Get Current Pre-Release
        id: current_release
        uses: joutvhu/get-release@v1
        with:
          debug: true
          latest: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Latest Pre-Release
        uses: duhow/download-github-release-assets@v1
        with:
          tag: ${{ steps.current_release.outputs.tag_name }}
          files: |
            burrito-linux-${{ steps.current_release.outputs.tag_name }}.zip
            burrito-win64-${{ steps.current_release.outputs.tag_name }}.zip
            burrito-win32-${{ steps.current_release.outputs.tag_name }}.zip
            burrito-mac64-${{ steps.current_release.outputs.tag_name }}.zip
          target: /var/tmp/

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir -pv release
          cd release
          tag=${{ steps.current_release.outputs.tag_name }}
          cp /var/tmp/burrito-${tag}-linux.zip ./burrito-linux-${{ github.ref_name }}.zip
          cp /var/tmp/burrito-${tag}-win64.zip ./burrito-win64-${{ github.ref_name }}.zip
          cp /var/tmp/burrito-${tag}-win32.zip ./burrito-win32-${{ github.ref_name }}.zip
          cp /var/tmp/burrito-${tag}-mac64.zip ./burrito-mac64-${{ github.ref_name }}.zip

      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          files: |
            release/*
